#### #loop #sequence #enumerate

In [1]:
seq = [1,4,1,5,9]

In [32]:
for e in seq:
    print(e)

kim
lee
park


In [31]:
for idx, val in enumerate(seq):
    print(idx, val)

0 kim
1 lee
2 park


In [5]:
str = 'abc'
str.upper()

'ABC'

In [6]:
str = 'abc'
str.capitalize()

'Abc'

In [8]:
str = 'nice to meet you. how are you'
str.capitalize()

'Nice to meet you. how are you'

#### #loop #dictionary 

In [13]:
seq = { 'kim':99, 'lee':97, 'park':95 }
seq

{'kim': 99, 'lee': 97, 'park': 95}

In [20]:
for key, val in seq:
    print(key, val)
    
# return error

ValueError: too many values to unpack (expected 2)

In [22]:
for key, val in enumerate(seq):
    print(key, val)

0 kim
1 lee
2 park


In [23]:
for key, val in seq.items():
    print(key, val)

kim 99
lee 97
park 95


#### #loop #numpy array

In [40]:
import numpy as np
npa = np.array([14, 15, 92, 65, 35])
npa

array([14, 15, 92, 65, 35])

In [41]:
for val in npa:
    print(val, end='  ')

14  15  92  65  35  

In [42]:
first_10 = np.array([14, 15, 92, 65, 35])
second_10 = np.array([89, 79, 32, 38, 46])
npa2d = np.array([first_10, second_10])
npa2d

array([[14, 15, 92, 65, 35],
       [89, 79, 32, 38, 46]])

In [43]:
for val in npa2d:
    print(val)
    print('*****')

[14 15 92 65 35]
*****
[89 79 32 38 46]
*****


In [44]:
for val in np.nditer(npa2d):
    print(val, end = '  ')

14  15  92  65  35  89  79  32  38  46  

#### #pd.read_csv

In [49]:
import pandas as pd

In [51]:
pd.read_csv('./sample_csv.csv')

col1  col2
0     1     1
1     2     2
2     3     3

In [52]:
pd.read_csv('./sample_csv.csv', index_col=0)

col2
col1      
1        1
2        2
3        3

In [53]:
pd.read_csv('./sample_csv.csv', index_col=1)

col1
col2      
1        1
2        2
3        3

#### #loop #DataFrame

In [55]:
df = pd.DataFrame({'no':[1,2,3,4],
                   'name':['Kim','Cris','John','Kesh'],
                   'score':[99,95,97,93]
                  })
df

no  name  score
0   1   Kim     99
1   2  Cris     95
2   3  John     97
3   4  Kesh     93

In [56]:
for val in df:
    print(val)

no
name
score


In [58]:
for label, row in df.iterrows():
    print(label, end='  ')

0  1  2  3  

In [66]:
for label, row in df.iterrows():
    print(row, end='\n------------------------\n')

no         1
name     Kim
score     99
Name: 0, dtype: object
------------------------
no          2
name     Cris
score      95
Name: 1, dtype: object
------------------------
no          3
name     John
score      97
Name: 2, dtype: object
------------------------
no          4
name     Kesh
score      93
Name: 3, dtype: object
------------------------


In [70]:
# select specific columns in a row
for label, row in df.iterrows():
    print(row['name'], end = '  ')

Kim  Cris  John  Kesh  

In [71]:
for label, row in df.iterrows():
    df.loc[label, 'name_length'] = len(row['name'])
df

no  name  score  name_length
0   1   Kim     99          3.0
1   2  Cris     95          4.0
2   3  John     97          4.0
3   4  Kesh     93          4.0

In [72]:
df['name_length_2'] = df['name'].apply(len)
df

no  name  score  name_length  name_length_2
0   1   Kim     99          3.0              3
1   2  Cris     95          4.0              4
2   3  John     97          4.0              4
3   4  Kesh     93          4.0              4

In [74]:
'aaa'.upper()

'AAA'

#### #random #np.random

In [76]:
import numpy as np

In [80]:
for i in range(3):
    print(np.random.rand(), end='  ')

0.3330154353907365  0.2898082862332061  0.5585013570804429  

In [86]:
for i in range(3):
    np.random.seed(141)   # reproductivity
    print(np.random.rand(), end='  ')

0.9173854839516489  0.9173854839516489  0.9173854839516489  

In [87]:
np.random.seed(141)
np.random.rand()

0.9173854839516489

In [88]:
np.random.rand()

0.5223948976356186

#### #random int in the range

In [95]:
for i in range(15):
    print(np.random.randint(0,5), end='  ')

2  2  1  0  3  3  4  4  1  3  2  2  0  0  3  