# Excercises

In [9]:
a = input()
a = int(a)
t = tuple(range(-10,10,a))
print(t)

2
(-10, -8, -6, -4, -2, 0, 2, 4, 6, 8)


In [4]:
k = input().split()
v = map(float, input().split())
d = dict(zip(k,v))
print(d)

a b c
10 20 30
{'a': 10.0, 'b': 20.0, 'c': 30.0}


In [3]:
n = int(input())
for i in range(1,10):
    print(n, "*", i, "=", n*i)

5
5  *  1  =  5
5  *  2  =  10
5  *  3  =  15
5  *  4  =  20
5  *  5  =  25
5  *  6  =  30
5  *  7  =  35
5  *  8  =  40
5  *  9  =  45


In [5]:
a = int(input())
b = input()
if b == 'Cash3000':
    print(a - 3000)
else :
    print(a - 5000)

72000
Cash5000
67000


In [9]:
a = input().split()

10


In [1]:
a = input().split()
a.

the grown-ups' response, this time, was to advise me to lay aside my drawings of boa constrictors, whether from the inside or the outside, and devote myself instead to geography, history, arithmetic, and grammar. That is why, at the, age of six, I gave up what might have been a magnificent career as a painter. I had been disheartened by the failure of my Drawing Number One and my Drawing Number Two. Grown-ups never understand anything by themselves, and it is tiresome for children to be always and forever explaining things to the.


In [10]:
paragraph = input().split()
# paragraph = "was to advise me to lay aside my drawings of boa constrictors, whether from the inside or the outside, and devote myself instead to geography, history, arithmetic, and grammar. That is why, at the, age of six, I gave up what might have been a magnificent career as a painter. I had been disheartened by the failure of my Drawing Number One and my Drawing Number Two. it is tiresome for children to be always and forever explaining things to the."
cnt = 0
for i in paragraph:
    if i.strip(',. ')=='the':
        cnt += 1
print(cnt)

the grown-ups' response, this time, was to advise me to lay aside my drawings of boa constrictors, whether from the inside or the outside, and devote myself instead to geography, history, arithmetic, and grammar. That is why, at the, age of six, I gave up what might have been a magnificent career as a painter. I had been disheartened by the failure of my Drawing Number One and my Drawing Number Two. Grown-ups never understand anything by themselves, and it is tiresome for children to be always and forever explaining things to the.
6


In [32]:
prices = map(int, input().split(';'))
li = list(prices)
li.sort(reverse=True)


#'51900;83000;158000;367500;250000;59200;128500;1304000'

51900;83000;158000;367500;250000;59200;128500;1304000


In [1]:
a = int(input())
while a >= 1350 :
    a -= 1350
    print(a)

10000
8650
7300
5950
4600
3250
1900
550


In [3]:
start, stop = 21,33
i = start
while True:
    if i%10 == 3:
        i += 1
        continue
    if i>stop :
        break
    print(i, end=' ')
    i += 1

21 22 24 25 26 27 28 29 30 31 32 

In [ ]:
for i in range(1, 101):
    if ①                          :
        print('FizzBuzz')
    elif ②          :
        print('Fizz')
    elif ③          :
        print('Buzz')
    else:
        print(i)
        
① i % 2 == 0 and i % 11 == 0
② i % 2 == 0
③ i % 11 == 0

In [3]:
a, b = map(int,input().split())
for i in range(a,b+1) :
    if i%5==0 and i%7==0 :
        print('FizzBuzz')
    elif i%5==0 :
        print("Fizz")
    elif i%7==0:
        print('Buzz')
    else:
        print(i)

10 20
Fizz
11
12
13
Buzz
Fizz
16
17
18
19


In [11]:
a, b = map(int, input().split())
li = [2**i for i in range(a,b+1)]
li.pop(1)
li.pop(-2)
print(li)

1 10
[2, 8, 16, 32, 64, 128, 256, 1024]


### sum of 약수

In [19]:
def sum_y(n):
    v = 0
    for i in range(1,n+1):
        if n%i == 0:
            v += i
            print(i)
    return v

sum_y(12)

1
2
3
4
6
12


28

In [ ]:
def sum_y(n):

In [ ]:
[i for i in range(1,n+1)]

#### filter : remain elements whose result is True

In [29]:
list(filter(lambda x : isinstance(x, str),['s',0,'1',2]))

['s', '1']

In [30]:
n = 6
sum(filter(  lambda x: not n%x, (i for i in range(1,n+1))  ))

12

#### generator vs. list의 차이

In [31]:
import sys

In [32]:
sys.getsizeof((i for i in range(1, n+190)))

112

In [34]:
sys.getsizeof([i for i in range(1, n+190)])

1664

#### ML recap

In [44]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder, MinMaxScaler ,StandardScaler

In [45]:
data = load_iris()

In [46]:
X, y = data.data, data.target

In [47]:
X.shape

(150, 4)

In [48]:
y.shape

(150,)

In [49]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [50]:
y[0]

0

#### Min Max Scaler 

max value = 1  
min value = 0  

In [157]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([1,2,5,8,9,10]).reshape(-1,1)  
print('--- orig. data ---'); print(data); print()
print('** shape :', data.shape)

scaler = MinMaxScaler(feature_range=(-1,1))
scaler.fit(data)
print('** min value :', scaler.data_min_)
print('** max value :', scaler.data_max_); print() ;
print('--- MinMax_Norm. Result ---'); 
mms_data = scaler.transform(data)
print(mms_data,'\n')

#################################################
################## code only ####################
import numpy as np
from sklearn.preprocessing import MinMaxScaler
data = np.array([1,2,5,8,9,10]).reshape(-1,1)  
scaler = MinMaxScaler(feature_range=(-1,1))
scaler.fit(data)
mms_data = scaler.transform(data)
mms_data
#################################################

--- orig. data ---
[[ 1]
 [ 2]
 [ 5]
 [ 8]
 [ 9]
 [10]]

** shape : (6, 1)
** min value : [1.]
** max value : [10.]

--- MinMax_Norm. Result ---
[[-1.        ]
 [-0.77777778]
 [-0.11111111]
 [ 0.55555556]
 [ 0.77777778]
 [ 1.        ]] 



array([[-1.        ],
       [-0.77777778],
       [-0.11111111],
       [ 0.55555556],
       [ 0.77777778],
       [ 1.        ]])

In [126]:
data = np.array([1,2,3,5,9,15,28,29,30]).reshape(-1,1)  # data : 5*1 shape
data.shape

(9, 1)

In [127]:
data

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 9],
       [15],
       [28],
       [29],
       [30]])

In [128]:
scaler = MinMaxScaler(feature_range=(-1,1))
scaler.fit(data)

MinMaxScaler(feature_range=(-1, 1))

In [129]:
print(scaler.data_max_)

[30.]


In [130]:
print(scaler.transform(data))

[[-1.        ]
 [-0.93103448]
 [-0.86206897]
 [-0.72413793]
 [-0.44827586]
 [-0.03448276]
 [ 0.86206897]
 [ 0.93103448]
 [ 1.        ]]


In [80]:
mms_X = mms.transform(x)
mms.fit(x)

MinMaxScaler(feature_range=(-1, 1))

In [82]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [66]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

minmax

In [83]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
print(scaler.fit(data))

# MinMaxScaler()
print(scaler.data_max_)
# [ 1. 18.]

print(scaler.transform(data))
# [[0.   0.  ]
#  [0.25 0.25]
#  [0.5  0.5 ]
#  [1.   1.  ]]

print(scaler.transform([[2, 2]]))
# [[1.5 0. ]]

MinMaxScaler()
[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[[1.5 0. ]]


In [ ]:
print(scaler.transform([[2, 2]]))